/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { WorkBlock, TagType, Task } from './types';

export const COLORS = {
  turquesa: { main: '#14B8A6', pastel: '#F0FDFA' },
  azul: { main: '#0EA5E9', pastel: '#F0F9FF' },
  morado: { main: '#A855F7', pastel: '#FAF5FF' },
  rosa: { main: '#EC4899', pastel: '#FDF2F8' },
  naranja: { main: '#F97316', pastel: '#FFF7ED' },
  lima: { main: '#84CC16', pastel: '#F7FEE7' },
  rojo: { main: '#EF4444', pastel: '#FEF2F2' },
  ambar: { main: '#F59E0B', pastel: '#FFFBEB' },
  indigo: { main: '#6366F1', pastel: '#EEF2FF' },
  esmeralda: { main: '#10B981', pastel: '#F0FDF4' },
  slate: { main: '#64748B', pastel: '#F8FAFC' },
  fucsia: { main: '#D946EF', pastel: '#FDF4FF' },
  cian: { main: '#06B6D4', pastel: '#ECFEFF' },
  violeta: { main: '#8B5CF6', pastel: '#F5F3FF' },
  oro: { main: '#EAB308', pastel: '#FEFCE8' },
  cobalto: { main: '#1D4ED8', pastel: '#EFF6FF' },
  carmesí: { main: '#BE123C', pastel: '#FFF1F2' },
  menta: { main: '#6EE7B7', pastel: '#F0FDF9' },
  lavanda: { main: '#A78BFA', pastel: '#F5F3FF' },
  ocre: { main: '#B45309', pastel: '#FFFBEB' },
};

export const TAG_LABELS: Record<TagType, { label: string, icon: string }> = {
  con_hora: { label: 'Con Hora', icon: '⏰' },
  focus: { label: 'Focus', icon: '🎯' },
  dirección: { label: 'Dirección', icon: '🚀' },
  espera: { label: 'En Espera', icon: '⏳' },
  resto: { label: 'Resto', icon: '📋' }
};

export const INITIAL_BLOCKS: WorkBlock[] = [
  { id: 'b1', name: 'Cuadro de Mando', color: COLORS.turquesa.main, pastelColor: COLORS.turquesa.pastel, icon: '📊', order: 1, isActive: true },
  { id: 'b2', name: 'Contabilidad central', color: COLORS.azul.main, pastelColor: COLORS.azul.pastel, icon: '💰', order: 2, isActive: true },
  { id: 'b3', name: 'Contabilidad Franquis', color: COLORS.morado.main, pastelColor: COLORS.morado.pastel, icon: '🏪', order: 3, isActive: true },
  { id: 'b4', name: 'Bancos', color: COLORS.naranja.main, pastelColor: COLORS.naranja.pastel, icon: '🏦', order: 4, isActive: true },
  { id: 'b5', name: 'Contratos', color: COLORS.rosa.main, pastelColor: COLORS.rosa.pastel, icon: '📜', order: 5, isActive: true },
  { id: 'b6', name: 'Finca', color: COLORS.lima.main, pastelColor: COLORS.lima.pastel, icon: '🏠', order: 6, isActive: true },
  { id: 'b7', name: 'RRHH', color: COLORS.azul.main, pastelColor: COLORS.azul.pastel, icon: '👥', order: 7, isActive: true },
  { id: 'b8', name: 'ERP', color: COLORS.turquesa.main, pastelColor: COLORS.turquesa.pastel, icon: '⚙️', order: 8, isActive: true },
  { id: 'b10', name: 'Seguros', color: COLORS.rosa.main, pastelColor: COLORS.rosa.pastel, icon: '🛡️', order: 10, isActive: true },
];

export const MOCK_TASKS: Record<string, Task> = {
  'tmpl-1': {
    id: 'tmpl-1',
    blockId: 'b1',
    title: 'Rutinas mañana',
    notes: 'Revisión técnica de márgenes y picking',
    priority: 'media',
    tags: ['con_hora'],
    status: 'pending',
    dueDate: null,
    estimatedMinutes: 45,
    order: 0,
    createdAt: new Date().toISOString(),
    modifiedAt: new Date().toISOString(),
    isTemplate: true,
    subtasks: ['tmpl-1-s1', 'tmpl-1-s2', 'tmpl-1-s3']
  },
  'tmpl-1-s1': {
    id: 'tmpl-1-s1',
    blockId: 'b1',
    parentTaskId: 'tmpl-1',
    title: 'Márgenes-Bancos',
    priority: 'media',
    status: 'pending',
    dueDate: null,
    estimatedMinutes: 15,
    order: 0,
    createdAt: new Date().toISOString(),
    modifiedAt: new Date().toISOString(),
    isTemplate: true,
    recurrence: { frequency: 'weekdays', startDate: '2026-04-01' },
    subtasks: [],
    tags: []
  },
  'tmpl-1-s2': {
    id: 'tmpl-1-s2',
    blockId: 'b1',
    parentTaskId: 'tmpl-1',
    title: 'Ingresos',
    priority: 'media',
    status: 'pending',
    dueDate: null,
    estimatedMinutes: 15,
    order: 1,
    createdAt: new Date().toISOString(),
    modifiedAt: new Date().toISOString(),
    isTemplate: true,
    recurrence: { frequency: 'weekdays', startDate: '2026-04-01' },
    subtasks: [],
    tags: []
  },
  'tmpl-1-s3': {
    id: 'tmpl-1-s3',
    blockId: 'b1',
    parentTaskId: 'tmpl-1',
    title: 'Picking',
    priority: 'media',
    status: 'pending',
    dueDate: null,
    estimatedMinutes: 15,
    order: 2,
    createdAt: new Date().toISOString(),
    modifiedAt: new Date().toISOString(),
    isTemplate: true,
    recurrence: { frequency: 'weekdays', startDate: '2026-04-01' },
    subtasks: [],
    tags: []
  },
  'tmpl-2': {
    id: 'tmpl-2',
    blockId: 'b4',
    title: 'Pagos Mes proveedores',
    notes: 'Ejecución de transferencias bancarias',
    priority: 'media',
    tags: ['con_hora'],
    status: 'pending',
    dueDate: null,
    estimatedMinutes: 60,
    order: 1,
    createdAt: new Date().toISOString(),
    modifiedAt: new Date().toISOString(),
    isTemplate: true,
    subtasks: ['tmpl-2-s1', 'tmpl-2-s2', 'tmpl-2-s3']
  },
  'tmpl-2-s1': {
    id: 'tmpl-2-s1',
    blockId: 'b4',
    parentTaskId: 'tmpl-2',
    title: 'Pago mercado 1Q',
    status: 'pending',
    dueDate: null,
    priority: 'media',
    estimatedMinutes: 20,
    order: 0,
    createdAt: new Date().toISOString(),
    modifiedAt: new Date().toISOString(),
    isTemplate: true,
    recurrence: { frequency: 'monthly', monthDay: 1, startDate: '2026-04-01' },
    subtasks: [],
    tags: []
  },
  'tmpl-2-s2': {
    id: 'tmpl-2-s2',
    blockId: 'b4',
    parentTaskId: 'tmpl-2',
    title: 'Actualizar vto 1Q',
    status: 'pending',
    dueDate: null,
    priority: 'media',
    estimatedMinutes: 20,
    order: 1,
    createdAt: new Date().toISOString(),
    modifiedAt: new Date().toISOString(),
    isTemplate: true,
    recurrence: { frequency: 'monthly', monthDay: 1, startDate: '2026-04-01' },
    subtasks: [],
    tags: []
  },
  'tmpl-2-s3': {
    id: 'tmpl-2-s3',
    blockId: 'b4',
    parentTaskId: 'tmpl-2',
    title: 'Pago Vto 7 del mes BSO',
    status: 'pending',
    dueDate: null,
    priority: 'media',
    estimatedMinutes: 20,
    order: 2,
    createdAt: new Date().toISOString(),
    modifiedAt: new Date().toISOString(),
    isTemplate: true,
    recurrence: { frequency: 'monthly', monthDay: 1, startDate: '2026-04-01' },
    subtasks: [],
    tags: []
  },
  't1': {
    id: 't1',
    blockId: 'b1',
    title: 'Tarea manual de prueba',
    notes: 'Esta tarea no es recurrente',
    priority: 'alta',
    tags: ['focus'],
    status: 'pending',
    dueDate: new Date().toLocaleDateString('en-CA'),
    estimatedMinutes: 30,
    order: 0,
    createdAt: new Date().toISOString(),
    modifiedAt: new Date().toISOString(),
    subtasks: []
  }
};
